name = "salla-gamification"
main = "src/index.ts"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# D1 Database configuration
[[d1_databases]]
binding = "GAMIFICATION_DB"
database_name = "gamification"
database_id = "cc10cf75-35c2-461a-a838-2488e6cfc424"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development" }

# Production configuration
[env.production]
vars = { ENVIRONMENT = "production" }